# 100 numpy exercises
以下はnumpyのメーリングリストやstack overflow，numpyのドキュメントから集められた問題集です．

練習と備忘録を兼ねてここにまとめます．

#### 1. Import the numpy packate under the name np (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration(★☆☆)

In [11]:
print(np.version.version)

1.11.3


#### model answer

In [13]:
print(np.__version__)
np.show_config()

1.11.3
blas_opt_info:
    include_dirs = ['/home/smjro/anaconda3/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/smjro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_mkl_info:
    include_dirs = ['/home/smjro/anaconda3/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/smjro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
lapack_opt_info:
    include_dirs = ['/home/smjro/anaconda3/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/smjro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    include_dirs = ['/home/smjro/anaconda3/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5

#### 3. Create a null vector of size 10(★☆☆)

In [20]:
A = np.empty(10)
print(A)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4. How to find the memory size of any array (★☆☆)

In [24]:
print(A.itemsize)  # 要素１つあたりのメモリ使用量（バイト単位）
print(A.nbytes)    # 全体におけるメモリ総量

8
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [33]:
# help(np.add)  # numpyにおいてhelp()は関数全体のdocを表示してしまう
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


#### model answer
-cのオプションを付けることで，コードを実行できる

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [34]:
B = np.zeros(10)
B[4] = 1
print(B)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [41]:
C = np.arange(10, 50)
print(C)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [45]:
print(C[::-1])  # C[start: stop: step] stepがマイナスの時は後ろから数える

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [59]:
D = np.arange(9)
print(D.reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [67]:
E = np.array([1,2,0,0,4,0])
print(E[E!=0])

[1 2 4]


#### model answer

In [73]:
E = np.nonzero([1,2,0,0,4,0])
print(E)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [78]:
F = np.identity(3)  # 行数と列数が同じ単位行列のみ生成可能
print(F)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### model answer

In [77]:
F = np.eye(3)  # 行数，列数を指定して単位行列を作成可能
print(F)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [82]:
np.random.rand(3, 3, 3)

array([[[ 0.91121544,  0.41723605,  0.83973321],
        [ 0.32693821,  0.91637654,  0.66153834],
        [ 0.13511519,  0.18084518,  0.02745482]],

       [[ 0.52763179,  0.92922322,  0.06593989],
        [ 0.41258538,  0.06998264,  0.22465454],
        [ 0.5486807 ,  0.40149427,  0.83821733]],

       [[ 0.00657458,  0.88976491,  0.38859431],
        [ 0.92378914,  0.57409148,  0.30585862],
        [ 0.2344521 ,  0.38370791,  0.64391118]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [88]:
G = np.random.randn(10, 10)
print("min:{}, max:{}".format(G.min(), G.max()))

min:-1.9784107833567208, max:2.253651497936991


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [98]:
H = np.random.normal(5, 2, 30)
print(H.mean())

5.19393166585


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [105]:
I = np.ones((4, 4))
I[1:-1,1:-1]=0
print(I)

[[ 1.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  1.  1.  1.]]
